checking if slug attribute exists
getattr raises  "AttributeError: 'xxxx' object has no attribute 'slug'" if the attribute does not exist. 
See https://docs.python.org/3/library/functions.html#getattr